###1
GET http://localhost:3001/states/

###2
GET http://localhost:3001/states/:stateId/

###3
POST  http://localhost:3001/districts/
Content_Type:application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

###4
GET http://localhost:3001/districts/:districtId/

###5
DELETE http://localhost:3001/districts/:districtId/

###6
PUT  http://localhost:3001/districts/:districtId/
Content-type:application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

###7
GET http://localhost:3001/states/:stateId/stats/

###8
GET http://localhost:3001/districts/:districtId/details/